import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import React, { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function fetchProducts() {
  const response = await fetch(
    "https://663ce76017145c4d8c381f97.mockapi.io/products"
  ); // change back later
  if (!response.ok) {
    throw new Error("Failed to fetch products");
  }
  return response.json();
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await fetchProducts();

  return (
    <html lang="en" data-theme="cupcake">
      <body className={inter.className}>
        <Navbar data={data} />
        {React.cloneElement(children as React.ReactElement, {
          data,
        })}
      </body>
    </html>
  );
}
